name: Publish Products to STAGING fiware-ops.github.io
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  refresh-page-data:
    name: Refresh PageData.js
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
       path: main
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: staging
        ref: gh-pages
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        cp -R main/marketplace staging
        cp -R main/community staging
    - name: Commit files
      continue-on-error: true
      run: |
        cd staging
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A *
        git commit -m "Update Staging" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        directory: staging
