name: Publish directory pages to LIVE fiware.org

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          target: ${{ secrets.SSH_DIR }}
          source: "directories/careers/**,directories/domains/**,directories/enablers/**,directories/ihubs/**,directories/impact-stories/**,directories/marketing-tools/**,directories/open-calls/**,directories/organisations/**,directories/research-development/**,directories/webinars"
